server:
  port: 8082

spring:
  application:
    name: project-service
    
  datasource:
    url: jdbc:h2:mem:projectdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
  security:
    oauth2:
      client:
        provider:
          auth0:
            issuer-uri: https://dev-74z0i7dvek4nks11.us.auth0.com/
        registration:
          auth0:
            client-id: N5dJ2gvrCspzgpYdvKCAotIdv7mNzAhg
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
      resourceserver:
        jwt:
          issuer-uri: https://dev-74z0i7dvek4nks11.us.auth0.com/
          audiences: https://api.taskflow.com
logging:
  level:
    org.springframework.security: DEBUG 